### ISSUE TITLE
Scrollable container clipping is broken with centerized sprites.

### ISSUE THREAD

**Issue by yuriks** [oddgames/UIToolkit#61]
If you put a centerized sprite inside a UIScrollableVerticalLayout, clipping is incorrect. Instead of correctly clipping the sprites, they seems to be clipped earlier or later than needed and slide around while doing so.

**Comment by nsxdavid** [comment]
Yup, I noticed that too.  The whole layout system is kind of broken to be honest. Concepts are overloaded to the point they conflict all over.

**Comment by xenonii** [comment]
In line 217 of UIAbstractContainer there is

```
                if (item.hidden) {
                    lastIndex--;
                }
```

For the case of using a UIScrollableVerticalLayout this shouldn't execute, as it would screw up the scroll vertical layout where items in the middle of the list would get drawn on each other. The anchor's OffsetY would be the same for that item when lastIndex and i coincide, since lastIndex is being decremented on each hidden item (and scroll view hides items when out of view).

**Comment by prime31** [comment]
xenonil is correct. the latest push has fixed this.
